replicaCount: 1

image:
  repository: ""
  registry: ghcr.io
  owner: canary-io
  name: ""
  tag: ""
  imagePullSecret: ""

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: proxy

ingress:
  className: nginx
  host: ""
  domain: orcademo.com
  annotations: {}

metrics:
  enabled: true
  host: ""
  path: /metrics
  annotations: {}

resources: {}


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

rollout:
  canary:
    enabled: false
    analysis:
      enabled: false
    steps: [25, 40, 75, 100]
  bluegreen:
    enabled: false

grafanaDashboard:
  enabled: true
  apiVersion: ""
  folder: ""
  labels: {}
  instanceSelector:
    matchLabels: {}
  ingress:
    enabled: true
    host: ""
    path: /
    annotations: {}
  service:
    name: prometheus-grafana
    namespace: monitoring
    port: 80

grafanaImportJob:
  enabled: true
  namespace: monitoring
  grafanaUrl: http://prometheus-grafana.monitoring.svc.cluster.local
  credentialsSecret:
    create: false
    name: grafana-import-credentials
    usernameKey: username
    passwordKey: password
    username: admin
    password: ""
