replicaCount: 1

image:
  repository: ""
  registry: ghcr.io
  owner: canary-io
  name: ""
  tag: ""
  imagePullSecret: ""

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: proxy

ingress:
  className: nginx
  host: ""
  domain: apps.local
  annotations: {}

resources: {}


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

rollout:
  canary:
    enabled: false
    steps: [25, 40, 75, 100]
  bluegreen:
    enabled: false

grafanaDashboard:
  enabled: false
  apiVersion: ""
  folder: ""
  labels: {}
  instanceSelector:
    matchLabels: {}

grafanaImportJob:
  enabled: false
  namespace: monitoring
  grafanaUrl: http://prometheus-grafana.monitoring.svc.cluster.local
  credentialsSecret:
    create: false
    name: grafana-import-credentials
    usernameKey: username
    passwordKey: password
    username: admin
    password: ""
