replicaCount: 1

image:
  name: ""
  tag: ""
  imagePullSecret: ""

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

rollout:
  canary:
    enabled: false
    steps: [25, 50, 75, 100]
  bluegreen:
    enabled: false