{{- if .Values.rollout.bluegreen.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.name" . }}-active
spec:
  type: ClusterIP
  selector:
    app: {{ include "service-chart.name" . }}
  ports:
    - port: 80
      targetPort: 8080
{{- end }}