{{- if .Values.rollout.bluegreen.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "service-chart.name" . }}
  namespace: argo-rollouts
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "service-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "service-chart.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      {{- if .Values.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}
      {{- end }}
      containers:
      - name:  {{ include "service-chart.name" . }}
        image:  "{{ include "service-chart.image" . }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: {{ include "service-chart.name" . }}-active
      previewService: {{ include "service-chart.name" . }}-preview
      autoPromotionEnabled: false
{{- end }}
