{{- if .Values.rollout.canary.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.canaryServiceName" . }}
  namespace: argo-rollouts
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "service-chart.name" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
