apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-creds-secret
  namespace: argo
type: kubernetes.io/dockerconfigjson

stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.image.imageCredentials.registry }}": {
          "username": "{{ .Values.image.imageCredentials.username }}",
          "password": "{{ .Values.image.imageCredentials.password }}",
          "email": "{{ .Values.image.imageCredentials.email }}",
          "auth": "{{ printf "%s:%s" .Values.image.imageCredentials.username .Values.image.imageCredentials.password | b64enc }}"
        }
      }
    }