{{- if and .Values.grafanaImportJob.enabled .Values.grafanaImportJob.credentialsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafanaImportJob.credentialsSecret.name }}
  namespace: {{ .Values.grafanaImportJob.namespace }}
type: Opaque
stringData:
  {{ .Values.grafanaImportJob.credentialsSecret.usernameKey }}: {{ .Values.grafanaImportJob.credentialsSecret.username | quote }}
  {{ .Values.grafanaImportJob.credentialsSecret.passwordKey }}: {{ .Values.grafanaImportJob.credentialsSecret.password | quote }}
{{- end }}
