apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service-chart.name" . }}-ingress
  namespace: argo-rollouts
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ include "service-chart.ingressHost" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ if .Values.rollout.bluegreen.enabled }}{{ include "service-chart.name" . }}-active{{ else }}{{ include "service-chart.name" . }}-stable{{ end }}
            port:
              number: 80
