apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service-chart.name" . }}
  namespace: argo-rollouts
spec:
  ingressClassName: nginx
  rules:
  - host: orca.{{ include "service-chart.name" . }}.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "service-chart.name" . }}-stable
            port:
              number: 80